# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "368fb974941b9e331b6c0899c2d520f1"
name = "SunGod External"
handle = "sungod-external"
application_url = "https://sg-shopify-external-c66be758fce5.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sg-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customer_events,read_discounts,read_metaobject_definitions,read_metaobjects,write_pixels"

[auth]
redirect_urls = [
  "https://sg-shopify-external-c66be758fce5.herokuapp.com/auth/callback",
  "https://sg-shopify-external-c66be758fce5.herokuapp.com/auth/shopify/callback",
  "https://sg-shopify-external-c66be758fce5.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
