api_version = "2024-07"

[[extensions]]
name = "Lite Packaging"
handle = "lite-packaging"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/LitePackaging.tsx"
target = "purchase.checkout.block.render"
[[extensions.targeting]]
module = "./src/LitePackaging.tsx"
target = "purchase.checkout.reductions.render-after"

[[extensions.settings.fields]]
key = "mobile_image"
type = "single_line_text_field"
name = "Mobile Image"
description = "Enter the Shopify Files link"
[[extensions.settings.fields]]
key = "desktop_image"
type = "single_line_text_field"
name = "Desktop Image"
description = "Enter the Shopify Files link"
[[extensions.settings.fields]]
key = "charity_info"
type = "multi_line_text_field"
name = "Charity Information Tooltip"
[[extensions.settings.fields]]
key = "charity_donation"
type = "number_decimal"
name = "Price in £ donated from each lite packaging item"

