type = "web_pixel_extension"
name = "custom-pixels"

runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.amplitudeAPIKey]
name = "Amplitude API Key"
description = "Amplitude API Key"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
